from detectron2.config import CfgNode as CN

def add_eov_config(cfg):
    cfg.MODEL.EOV_SEG = CN()
    cfg.MODEL.EOV_SEG.SIZE_DIVISIBILITY = 32
    cfg.MODEL.EOV_SEG.NUM_CLASSES = 133
    cfg.MODEL.EOV_SEG.NUM_STAGES = 2
    
    cfg.MODEL.EOV_SEG.IN_FEATURES = ["res2", "res3", "res4", "res5"]
    cfg.MODEL.EOV_SEG.HIDDEN_DIM = 256
    cfg.MODEL.EOV_SEG.AGG_DIM = 128
    cfg.MODEL.EOV_SEG.NUM_PROPOSALS = 100
    cfg.MODEL.EOV_SEG.CONV_KERNEL_SIZE_2D = 1
    cfg.MODEL.EOV_SEG.CONV_KERNEL_SIZE_1D = 3
    cfg.MODEL.EOV_SEG.NUM_CLS_FCS = 1
    cfg.MODEL.EOV_SEG.NUM_MASK_FCS = 1

    cfg.MODEL.EOV_SEG.NO_OBJECT_WEIGHT = 0.1
    cfg.MODEL.EOV_SEG.CLASS_WEIGHT = 2.0
    cfg.MODEL.EOV_SEG.MASK_WEIGHT = 5.0
    cfg.MODEL.EOV_SEG.DICE_WEIGHT = 5.0
    cfg.MODEL.EOV_SEG.TRAIN_NUM_POINTS = 112 * 112
    cfg.MODEL.EOV_SEG.OVERSAMPLE_RATIO = 3.0
    cfg.MODEL.EOV_SEG.IMPORTANCE_SAMPLE_RATIO = 0.75
    cfg.MODEL.EOV_SEG.TEMPERATIRE = 0.1

    cfg.MODEL.EOV_SEG.TEST = CN()
    cfg.MODEL.EOV_SEG.TEST.SEMANTIC_ON = False
    cfg.MODEL.EOV_SEG.TEST.INSTANCE_ON = False
    cfg.MODEL.EOV_SEG.TEST.PANOPTIC_ON = False
    cfg.MODEL.EOV_SEG.TEST.OBJECT_MASK_THRESHOLD = 0.0
    cfg.MODEL.EOV_SEG.TEST.OVERLAP_THRESHOLD = 0.0
    cfg.MODEL.EOV_SEG.TEST.SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE = False
    
    cfg.SOLVER.OPTIMIZER = "ADAMW"
    cfg.SOLVER.BACKBONE_MULTIPLIER = 0.1
    cfg.SOLVER.WEIGHT_DECAY_EMBED = 0.0
    cfg.SOLVER.WEIGHT_DECAY_BIAS = None
    
    cfg.SOLVER.POLY_LR_POWER = 0.9
    cfg.SOLVER.POLY_LR_CONSTANT_ENDING = 0.0

    cfg.INPUT.DATASET_MAPPER_NAME = "coco_panoptic_lsj"
    cfg.INPUT.SIZE_DIVISIBILITY = -1
    cfg.INPUT.COLOR_AUG_SSD = False
    cfg.INPUT.CROP.SINGLE_CATEGORY_MAX_AREA = 1.0

    cfg.INPUT.IMAGE_SIZE = 1024
    cfg.INPUT.MIN_SCALE = 0.1
    cfg.INPUT.MAX_SCALE = 2.0

    # ov head config
    cfg.MODEL.CLIP_BACKBONE = CN()
    cfg.MODEL.CLIP_BACKBONE.NAME = "CLIP"

    cfg.MODEL.OV_HEAD = CN()
    cfg.MODEL.OV_HEAD.CLIP_MODEL_NAME = "RN50"
    cfg.MODEL.OV_HEAD.CLIP_PRETRAINED_WEIGHTS = "openai"
    cfg.MODEL.OV_HEAD.CLIP_VIT_MODEL_NAME = "ViT-B-16"
    cfg.MODEL.OV_HEAD.CLIP_VIT_PRETRAINED_WEIGHTS = "openai"
    cfg.MODEL.OV_HEAD.EMBED_DIM = 768
    cfg.MODEL.OV_HEAD.GEOMETRIC_ENSEMBLE_ALPHA = 0.4
    cfg.MODEL.OV_HEAD.GEOMETRIC_ENSEMBLE_BETA = 0.8
    cfg.MODEL.OV_HEAD.ENSEMBLE_ON_VALID_MASK = False
