_BASE_: R50.yaml
DATASETS:
  TRAIN: ("openvocab_coco_2017_train_panoptic_with_sem_seg",)  # stuff: openvocab_coco_2017_train_stuff_sem_seg
  TEST: ("openvocab_ade20k_panoptic_val",)
MODEL:
  BACKBONE:
    NAME: "CLIP"
  WEIGHTS: ""
  EOV_SEG:
    NUM_PROPOSALS: 100
    NUM_STAGES: 3
    AGG_DIM: 128
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: True
      OBJECT_MASK_THRESHOLD: 0.0
  OV_HEAD:
    CLIP_MODEL_NAME: "RN101"
    CLIP_PRETRAINED_WEIGHTS: "openai"
    CLIP_VIT_MODEL_NAME: "ViT-B-16"
    CLIP_VIT_PRETRAINED_WEIGHTS: "openai"
    EMBED_DIM: 512
    ENSEMBLE_ON_VALID_MASK: True
    GEOMETRIC_ENSEMBLE_ALPHA: 0.4
    GEOMETRIC_ENSEMBLE_BETA: 0.8
OUTPUT_DIR: "output/eov_seg_r101"